# Generated by Django 4.0.2 on 2022-02-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='book_registered',
            field=models.ManyToManyField(blank=True, to='schools.Book'),
        ),
        migrations.AddField(
            model_name='reader',
            name='category_preference',
            field=models.ManyToManyField(blank=True, to='schools.Category'),
        ),
        migrations.AddField(
            model_name='reader',
            name='reading',
            field=models.ManyToManyField(blank=True, to='schools.Reading'),
        ),
        migrations.AddField(
            model_name='reader',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
