# Generated by Django 4.0.2 on 2022-02-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('approval', models.BooleanField(default=False, help_text='Approval to display the book')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('statut', models.CharField(default='Public', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Library', verbose_name='Library Image')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField()),
                ('location', models.ManyToManyField(to='schools.Location')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='Kinshasa', max_length=100, null=True)),
                ('country', models.CharField(default='Democratic Republic of Congo', max_length=100)),
                ('address', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('url', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('library', models.ManyToManyField(blank=True, default=None, to='schools.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('like', models.SmallIntegerField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.book')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='shelf',
            field=models.ManyToManyField(to='schools.Shelf'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('reply', models.ManyToManyField(blank=True, to='schools.Comment')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.reader')),
            ],
        ),
        migrations.CreateModel(
            name='BookAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('published_date', models.DateField(null=True)),
                ('published_date_type', models.CharField(blank=True, max_length=20, null=True)),
                ('page_count', models.IntegerField(blank=True, default=None, null=True)),
                ('imageCover', models.ImageField(blank=True, default=None, null=True, upload_to='covers', verbose_name='Book Cover')),
                ('previewLink', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('id_google_book', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ISBN_10', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('ISBN_13', models.CharField(blank=True, default=None, max_length=13, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to='eBooks')),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ManyToManyField(to='account.Author')),
                ('category', models.ManyToManyField(to='schools.Category')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.language')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(blank=True, to='schools.Comment'),
        ),
        migrations.AddField(
            model_name='book',
            name='data',
            field=models.ForeignKey(help_text='Book data', on_delete=django.db.models.deletion.CASCADE, to='schools.bookabstract'),
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.ForeignKey(help_text='Book Location in the library', on_delete=django.db.models.deletion.CASCADE, to='schools.location'),
        ),
    ]
